services:
  user-event-processor:
    build:
      context: ./UserEventProcessor
      dockerfile: Dockerfile
    depends_on:
      - kafka-broker
      - postgres-db
    environment:
      - DOTNET_ENVIRONMENT=Production
      - Kafka__BootstrapServers=kafka-broker:29092 
      - Kafka__Topic=user-events
      - Kafka__GroupId=user-event-processor-group
      - ConnectionStrings__Postgres=Host=postgres-db;Port=5432;Database=user_events_db;Username=postgres;Password=postgres
    restart: unless-stopped
    
  postgres-db:
    image: postgres:16
    environment:
      - POSTGRES_DB=user_events_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    restart: unless-stopped
    
  kafka-broker:
    image: confluentinc/cp-kafka:7.5.3
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" 
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_CREATE_TOPICS="user-events:1:1"
    restart: unless-stopped

volumes:
  postgres-data: 