// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserEventProcessor.Data;

#nullable disable

namespace UserEventProcessor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250716101248_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserEventProcessor.Models.UserEventStat", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.Property<string>("EventType")
                        .HasColumnType("text")
                        .HasColumnName("event_type")
                        .HasAnnotation("Relational:JsonPropertyName", "eventType");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count")
                        .HasAnnotation("Relational:JsonPropertyName", "count");

                    b.HasKey("UserId", "EventType");

                    b.ToTable("user_event_stats", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
